version: '3.8'

services:
  app:
    image: node:20.17.0
    container_name: nest_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file: .env
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: